CREATE DATABASE [ahm]
go

ALTER DATABASE [ahm] SET COMPATIBILITY_LEVEL = 100
go

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	BEGIN
		EXEC [ahm].[dbo].[sp_fulltext_database] @action = 'enable';
	END
go

ALTER DATABASE [ahm] SET ANSI_NULL_DEFAULT OFF
go

ALTER DATABASE [ahm] SET ANSI_NULLS OFF
go

ALTER DATABASE [ahm] SET ANSI_PADDING OFF
go

ALTER DATABASE [ahm] SET ANSI_WARNINGS OFF
go

ALTER DATABASE [ahm] SET ARITHABORT OFF
go

ALTER DATABASE [ahm] SET AUTO_CLOSE OFF
go

ALTER DATABASE [ahm] SET AUTO_SHRINK OFF
go

ALTER DATABASE [ahm] SET AUTO_UPDATE_STATISTICS ON
go

ALTER DATABASE [ahm] SET CURSOR_CLOSE_ON_COMMIT OFF
go

ALTER DATABASE [ahm] SET CURSOR_DEFAULT GLOBAL
go

ALTER DATABASE [ahm] SET CONCAT_NULL_YIELDS_NULL OFF
go

ALTER DATABASE [ahm] SET NUMERIC_ROUNDABORT OFF
go	

ALTER DATABASE [ahm] SET QUOTED_IDENTIFIER OFF
go

ALTER DATABASE [ahm] SET RECURSIVE_TRIGGERS OFF
go

ALTER DATABASE [ahm] SET DISABLE_BROKER
go

ALTER DATABASE [ahm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
go

ALTER DATABASE [ahm] SET DATE_CORRELATION_OPTIMIZATION OFF
go

ALTER DATABASE [ahm] SET TRUSTWORTHY OFF
go

ALTER DATABASE [ahm] SET ALLOW_SNAPSHOT_ISOLATION OFF
go

ALTER DATABASE [ahm] SET PARAMETERIZATION SIMPLE
go

ALTER DATABASE [ahm] SET READ_COMMITTED_SNAPSHOT OFF
go

ALTER DATABASE [ahm] SET HONOR_BROKER_PRIORITY OFF
go

ALTER DATABASE [ahm] SET RECOVERY SIMPLE
go

ALTER DATABASE [ahm] SET MULTI_USER
go

ALTER DATABASE [ahm] SET PAGE_VERIFY CHECKSUM
go

ALTER DATABASE [ahm] SET DB_CHAINING OFF
go

ALTER DATABASE [ahm] SET READ_WRITE
go

USE ahm;
CREATE TABLE TODO
( 
	id            integer IDENTITY ( 1,1 ) ,
	text              text  NULL 
)
go